# Generated by Django 5.1.4 on 2024-12-31 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_remove_user_groups_remove_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('patent_number', models.CharField(blank=True, max_length=100, null=True)),
                ('brief_description', models.TextField()),
                ('application_number', models.CharField(blank=True, max_length=100, null=True)),
                ('problem_statement', models.TextField()),
                ('solution', models.TextField()),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], max_length=10)),
                ('details', models.TextField(blank=True, null=True)),
                ('fund', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('category', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='idea_photos/')),
                ('video', models.FileField(blank=True, null=True, upload_to='idea_videos/')),
                ('team_info', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
