# Generated by Django 5.1.4 on 2025-01-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='posted_date',
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.CharField(default='Not Specified', max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=models.CharField(max_length=200),
        ),
    ]
