# Generated by Django 5.1.4 on 2025-01-04 11:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_job_posted_date_job_salary_alter_job_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='posted_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
