# Generated by Django 5.1.4 on 2025-01-07 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_job_posted_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('project_type', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timeline', models.DateField()),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('expertise_required', models.TextField()),
                ('payment_terms', models.TextField()),
                ('nda_required', models.BooleanField(default=False)),
                ('confidentiality_required', models.BooleanField(default=False)),
                ('ip_rights_required', models.BooleanField(default=False)),
                ('custom_field', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
